name: binder-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - xarray
  - matplotlib
  - cartopy
  - numpy
  - geopandas
  - netcdf4
  - jupyterlab
  - h5netcdf
  - scipy
  - numpy
  - geopandas
  - requests
  - pandas
  - requests
  - flox
